package frc.team972.robot.statemachines;

public enum SuperstructureState {
    READY_WRIST_RAISE, READY_WRIST_FLAT, READY_WRIST_LIP, READY_WRIST_LIP_HATCH, STOW_WRIST,
                       INTAKE_BALL_WRIST_FLAT, INTAKE_BALL_WRIST_LIP,
    READY_BALL_LEVEL_1, READY_BALL_LEVEL_2, READY_BALL_LEVEL_3,
    PREPARE_HATCH_INTAKE,
    READY_HATCH_LEVEL_1, READY_HATCH_LEVEL_2, READY_HATCH_LEVEL_3,

}
